"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  ExternalLink, Github, ChevronDown, ChevronRight,
  CheckCircle2, Terminal, Shield, Database, Zap,
  Users, Video, Mail, Brain, Upload,
  MessageSquare, Bell, FileText, BarChart3,
  Stethoscope, UserCheck, Settings, Activity,
  Lock, Server, Globe, Layers,
} from "lucide-react";
import { staggerContainer, cardReveal, fadeInUp } from "@/lib/animations";

// ─── Constants ────────────────────────────────────────────────────────────────
const LINKS = {
  live: "https://medsync-topaz.vercel.app",
  api:  "https://medsync-api-ic46.onrender.com",
  github: "https://github.com/Krishfefar11/MedSync",
};

const METRICS = [
  { value: "3",    label: "User Roles",         icon: Users,     color: "#2563eb" },
  { value: "15+",  label: "API Route Groups",    icon: Server,    color: "#0891b2" },
  { value: "10+",  label: "Core Features",       icon: Zap,       color: "#7c3aed" },
  { value: "11",   label: "DB Models (Prisma)",  icon: Database,  color: "#16a34a" },
];

const TECH = [
  { name: "Next.js 16",  color: "#ffffff" },
  { name: "TypeScript",  color: "#3178c6" },
  { name: "Tailwind CSS",color: "#38bdf8" },
  { name: "shadcn/ui",   color: "#ffffff" },
  { name: "Framer Motion",color:"#ff0055" },
  { name: "Node.js",     color: "#339933" },
  { name: "Express 5",   color: "#ffffff" },
  { name: "Prisma",      color: "#5a67d8" },
  { name: "PostgreSQL",  color: "#4479a1" },
  { name: "Socket.io",   color: "#010101" },
  { name: "Zoom API",    color: "#2D8CFF" },
  { name: "Gemini AI",   color: "#4285F4" },
  { name: "Cloudinary",  color: "#3448c5" },
  { name: "Resend",      color: "#ffffff" },
  { name: "Google OAuth",color: "#4285F4" },
  { name: "Neon DB",     color: "#00E5BF" },
];

const PORTALS = [
  {
    role: "Patient",
    icon: Users,
    color: "#2563eb",
    glow: "rgba(37,99,235,0.15)",
    gradient: "from-blue-600 to-blue-500",
    features: [
      { icon: BarChart3,    label: "Dashboard",       desc: "Stat cards, quick actions, upcoming appointments, vitals summary" },
      { icon: Stethoscope,  label: "Book Appointment",desc: "Choose doctor, specialty, date/time, consultation type (in-person or video)" },
      { icon: Upload,       label: "Health Records",  desc: "Upload medical docs to Cloudinary. AI parse button for lab reports via Gemini" },
      { icon: Activity,     label: "Vitals Tracking", desc: "Log blood pressure, weight, blood sugar, O₂ saturation with timestamp history" },
      { icon: FileText,     label: "EMR / Prescriptions", desc: "View doctor-written records. Download as professionally formatted PDF" },
      { icon: MessageSquare,label: "Real-time Chat",  desc: "Socket.io chat with treating doctor, scoped per appointment" },
      { icon: Bell,         label: "Notifications",   desc: "In-app feed: appointment confirmed/cancelled, new messages" },
      { icon: Lock,         label: "Forgot Password", desc: "Email-based reset flow — 64-char hex token, 1hr expiry, via Resend" },
    ],
  },
  {
    role: "Doctor",
    icon: Stethoscope,
    color: "#0891b2",
    glow: "rgba(8,145,178,0.15)",
    gradient: "from-cyan-600 to-cyan-500",
    features: [
      { icon: BarChart3,   label: "Dashboard",       desc: "Total patients, today's schedule, pending confirmations, completed count" },
      { icon: UserCheck,   label: "Appointments",    desc: "View pending/confirmed/completed. Confirm button triggers Zoom creation + patient email" },
      { icon: FileText,    label: "Write EMR",       desc: "Chief complaint, symptoms, diagnosis tags, medicines table, lab orders, follow-up date" },
      { icon: Users,       label: "Patient History", desc: "Full appointment history and past EMRs for returning patients" },
      { icon: Video,       label: "Zoom Integration",desc: "Meeting URL + password auto-generated by Zoom API, emailed to patient on confirm" },
    ],
  },
  {
    role: "Admin",
    icon: Settings,
    color: "#7c3aed",
    glow: "rgba(124,58,237,0.15)",
    gradient: "from-violet-600 to-violet-500",
    features: [
      { icon: BarChart3,   label: "Platform Stats",  desc: "Total patients, doctors (pending/approved), appointments, EMRs, 7-day registrations" },
      { icon: UserCheck,   label: "Doctor Approval", desc: "Review doctor registrations. Approve or reject with one click" },
      { icon: Users,       label: "User Management", desc: "View all patients and doctors with full profile data" },
      { icon: Activity,    label: "Analytics",       desc: "Appointment and registration trend data across the platform" },
    ],
  },
];

const INTEGRATIONS = [
  {
    icon: Video,
    name: "Zoom API",
    type: "Server-to-Server OAuth",
    color: "#2D8CFF",
    desc: "Fresh bearer token fetched per request (1hr TTL). Appointment confirm → creates meeting → stores zoomLink + password → emails patient. All in a single transaction.",
  },
  {
    icon: Brain,
    name: "Google Gemini AI",
    type: "1.5 Flash",
    color: "#4285F4",
    desc: "Lab report PDFs uploaded to Cloudinary → Gemini 1.5 Flash parses and extracts structured medical data (test names, values, reference ranges) — one click from the Health Records page.",
  },
  {
    icon: Mail,
    name: "Resend",
    type: "Transactional Email",
    color: "#ffffff",
    desc: "Appointment confirmations with Zoom link, password reset flow, doctor approval notifications — all templated and sent via Resend API.",
  },
  {
    icon: Upload,
    name: "Cloudinary",
    type: "File Storage CDN",
    color: "#3448c5",
    desc: "Medical documents and lab reports stored with Cloudinary's transformation API. Secure signed uploads from the patient portal.",
  },
  {
    icon: Globe,
    name: "Google OAuth",
    type: "Social Login",
    color: "#4285F4",
    desc: "Google ID token sent to backend → verified with google-auth-library → upserts User row → returns JWT access + refresh token pair.",
  },
  {
    icon: FileText,
    name: "@react-pdf/renderer",
    type: "Client-side PDF",
    color: "#e63946",
    desc: "Prescriptions and EMRs downloadable as professionally formatted PDFs — dynamically imported with { ssr: false } to avoid server-side crashes.",
  },
];

const CHALLENGES = [
  {
    title: "Render Production Build Failure",
    category: "DevOps",
    categoryColor: "#f59e0b",
    problem: "Render sets NODE_ENV=production, causing npm install to skip devDependencies. TypeScript compilation failed because @types/* and ts-node were in devDependencies — not available at build time.",
    solution: "Moved ALL packages (including @types/*, nodemon, ts-node, typescript) into dependencies, leaving devDependencies empty. Ensures the production build can compile.",
    code: `// package.json — all in "dependencies", not "devDependencies"
"typescript": "^5.0.0",
"@types/node": "^20.0.0",
"@types/express": "^4.17.21",
"ts-node": "^10.9.2"`,
  },
  {
    title: "CORS Blocking Vercel → Render",
    category: "Networking",
    categoryColor: "#ef4444",
    problem: "After deploying to Vercel, every API request was blocked with 'No Access-Control-Allow-Origin'. The FRONTEND_URL env var on Render was still pointing to localhost:3000.",
    solution: "Updated FRONTEND_URL on Render to the Vercel production URL. Refactored allowedOrigins to support comma-separated URLs for simultaneous local + prod access.",
    code: `// Allow multiple origins from one env var
const origins = process.env.FRONTEND_URL?.split(',') ?? [];
app.use(cors({ origin: origins, credentials: true }));`,
  },
  {
    title: "PDF Download Crash (ie is not a function)",
    category: "React / SSR",
    categoryColor: "#8b5cf6",
    problem: "PrescriptionPDF was wrapped with Next.js dynamic(), making it a lazy wrapper — not a real PDF component. PDFDownloadLink crashed trying to process the document tree.",
    solution: "Removed the inner dynamic() on PrescriptionPDF. The parent page component already loads with { ssr: false }, so @react-pdf/renderer never runs server-side regardless.",
    code: `// ❌ Before — double-wrapping broke the PDF tree
const PrescriptionPDF = dynamic(() => import('./prescription-pdf'));

// ✅ After — direct import is fine, parent already ssr:false
import PrescriptionPDF from './prescription-pdf';`,
  },
  {
    title: "Framer Motion TypeScript Error",
    category: "TypeScript",
    categoryColor: "#3b82f6",
    problem: "Framer Motion's ease property typed as Easing[] rejected a number[] cubic-bezier array, causing a TypeScript build failure on Vercel.",
    solution: "Changed the custom cubic-bezier to a named easing string that satisfies Framer Motion's type system.",
    code: `// ❌ Before — TS error: number[] not assignable to Easing
ease: [0.25, 0.46, 0.45, 0.94]

// ✅ After — named string satisfies Easing type
ease: 'easeOut' as const`,
  },
  {
    title: "Vercel 404 on Monorepo Deploy",
    category: "Deployment",
    categoryColor: "#16a34a",
    problem: "Monorepo has both backend/ and frontend/ folders. Vercel looked for a Next.js app at the repo root, returning 404 NOT_FOUND on all routes after deploy.",
    solution: "Set Root Directory to 'frontend' in Vercel project settings — Vercel now treats frontend/ as the project root for build and routing.",
    code: `// vercel.json at repo root
{
  "rootDirectory": "frontend",
  "framework": "nextjs"
}`,
  },
  {
    title: "Zoom Server-to-Server OAuth",
    category: "Integration",
    categoryColor: "#2D8CFF",
    problem: "Zoom Server-to-Server OAuth tokens expire in 1 hour. Meeting creation must happen atomically with appointment confirmation and patient email — any failure leaves the appointment in a broken state.",
    solution: "Zoom controller fetches a fresh OAuth token before each API call. Confirmation endpoint creates meeting, stores zoomLink + password, and fires the email — all in one Prisma transaction.",
    code: `// Atomic confirmation flow
const token = await getZoomAccessToken(); // fresh every call
const meeting = await createZoomMeeting(token, appointment);
await prisma.appointment.update({
  where: { id },
  data: { status: 'CONFIRMED', zoomLink: meeting.join_url,
          zoomPassword: meeting.password }
});
await sendConfirmationEmail(patient, meeting); // Resend`,
  },
];

const NUMBERS = [
  { value: "3",    label: "User Roles" },
  { value: "15+",  label: "API Route Groups" },
  { value: "11",   label: "Prisma DB Models" },
  { value: "6",    label: "Third-party APIs" },
  { value: "100%", label: "TypeScript" },
  { value: "6",    label: "Prod Bugs Fixed" },
  { value: "2",    label: "Deploy Platforms" },
  { value: "10+",  label: "Core Features" },
];

// ─── Sub-components ───────────────────────────────────────────────────────────

function LiveBadge() {
  return (
    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold"
      style={{ background: "rgba(22,163,74,0.12)", color: "#16a34a", border: "1px solid rgba(22,163,74,0.25)" }}>
      <span className="relative flex h-1.5 w-1.5">
        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75" />
        <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-green-400" />
      </span>
      LIVE IN PRODUCTION
    </span>
  );
}

function CodeBlock({ code, label }: { code: string; label: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="rounded-xl overflow-hidden border border-white/[0.07] mt-3">
      <div className="flex items-center justify-between px-4 py-2 bg-white/[0.04] border-b border-white/[0.06]">
        <div className="flex items-center gap-2">
          <div className="w-2.5 h-2.5 rounded-full bg-red-500/50" />
          <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/50" />
          <div className="w-2.5 h-2.5 rounded-full bg-green-500/50" />
          <span className="ml-1.5 text-[10px] text-slate-500 font-mono">{label}</span>
        </div>
        <motion.button
          onClick={() => { navigator.clipboard.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
          className="text-[10px] text-slate-500 hover:text-slate-300 transition-colors flex items-center gap-1"
          whileTap={{ scale: 0.95 }}
        >
          {copied ? <CheckCircle2 size={10} className="text-emerald-400" /> : <Terminal size={10} />}
          {copied ? "Copied" : "Copy"}
        </motion.button>
      </div>
      <pre className="p-4 text-[11px] leading-relaxed overflow-x-auto bg-black/30 font-mono text-slate-300 whitespace-pre-wrap">{code}</pre>
    </div>
  );
}

function ArchDiagram() {
  const layers = [
    { label: "Browser", tech: "Next.js 16 App Router", host: "Vercel CDN", icon: Globe, color: "#2563eb" },
    { label: "API Server", tech: "Node.js + Express 5  ·  Socket.io", host: "Render Web Service", icon: Server, color: "#0891b2" },
    { label: "Database", tech: "PostgreSQL via Prisma ORM", host: "Neon Serverless", icon: Database, color: "#16a34a" },
  ];

  return (
    <div className="p-6 rounded-2xl glass border border-white/[0.07] overflow-hidden relative">
      <div className="absolute inset-0 pointer-events-none"
        style={{ background: "radial-gradient(circle at 50% 50%, rgba(37,99,235,0.05) 0%, transparent 70%)" }} />
      <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-6 text-center">System Architecture</p>

      <div className="flex flex-col items-center gap-0">
        {layers.map((layer, i) => (
          <div key={layer.label} className="flex flex-col items-center w-full">
            <motion.div
              className="w-full max-w-lg px-5 py-4 rounded-xl flex items-center gap-4"
              style={{ background: `${layer.color}12`, border: `1px solid ${layer.color}30` }}
              whileHover={{ scale: 1.02 }}
            >
              <div className="w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0"
                style={{ background: `${layer.color}20` }}>
                <layer.icon size={17} style={{ color: layer.color }} />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-bold text-white">{layer.tech}</p>
                <p className="text-[10px]" style={{ color: layer.color }}>{layer.host}</p>
              </div>
              <span className="text-[10px] font-mono text-slate-500 flex-shrink-0">{layer.label}</span>
            </motion.div>

            {i < layers.length - 1 && (
              <div className="flex flex-col items-center py-1">
                <div className="w-px h-4" style={{ background: `linear-gradient(180deg, ${layer.color}60, ${layers[i+1].color}60)` }} />
                <ChevronRight size={10} className="text-slate-600 rotate-90" />
                <span className="text-[9px] font-mono text-slate-600 mt-0.5">
                  {i === 0 ? "REST / WebSocket" : "Prisma Client"}
                </span>
                <div className="w-px h-4" style={{ background: `linear-gradient(180deg, ${layer.color}40, ${layers[i+1].color}60)` }} />
              </div>
            )}
          </div>
        ))}
      </div>

      {/* External services row */}
      <div className="mt-6 pt-5 border-t border-white/[0.05]">
        <p className="text-[10px] font-mono text-slate-600 text-center uppercase tracking-widest mb-4">External Services (API Server integrates with)</p>
        <div className="flex flex-wrap justify-center gap-2">
          {[
            { name: "Zoom API", color: "#2D8CFF" },
            { name: "Gemini AI", color: "#4285F4" },
            { name: "Resend", color: "#94a3b8" },
            { name: "Cloudinary", color: "#3448c5" },
            { name: "Google OAuth", color: "#4285F4" },
          ].map(s => (
            <span key={s.name} className="px-3 py-1.5 rounded-lg text-[10px] font-medium"
              style={{ background: `${s.color}12`, color: s.color, border: `1px solid ${s.color}25` }}>
              {s.name}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────
export default function MedSyncShowcase() {
  const [activePortal, setActivePortal] = useState(0);
  const [expandedChallenge, setExpandedChallenge] = useState<number | null>(null);

  return (
    <motion.div
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true, margin: "-60px" }}
      variants={staggerContainer}
      className="relative"
    >
      {/* ── HERO HEADER ──────────────────────────────────────────────────── */}
      <motion.div
        variants={fadeInUp}
        className="relative rounded-3xl overflow-hidden border border-white/[0.08] mb-6"
        style={{ background: "linear-gradient(135deg, rgba(37,99,235,0.1) 0%, rgba(8,145,178,0.06) 50%, rgba(124,58,237,0.08) 100%)" }}
      >
        {/* Glow orbs */}
        <div className="absolute top-0 right-0 w-96 h-96 pointer-events-none"
          style={{ background: "radial-gradient(circle at 100% 0%, rgba(37,99,235,0.2) 0%, transparent 60%)" }} />
        <div className="absolute bottom-0 left-0 w-80 h-80 pointer-events-none"
          style={{ background: "radial-gradient(circle at 0% 100%, rgba(8,145,178,0.12) 0%, transparent 60%)" }} />

        <div className="relative z-10 p-8 md:p-12">
          {/* Badges */}
          <div className="flex flex-wrap items-center gap-3 mb-6">
            <span className="text-xs font-mono font-semibold uppercase tracking-[0.2em] text-slate-500">Featured Project</span>
            <LiveBadge />
            <span className="px-2.5 py-1 rounded-full text-xs font-medium"
              style={{ background: "rgba(37,99,235,0.15)", color: "#60a5fa", border: "1px solid rgba(37,99,235,0.3)" }}>
              Healthcare SaaS · Full-Stack
            </span>
            <span className="px-2.5 py-1 rounded-full text-xs font-medium"
              style={{ background: "rgba(124,58,237,0.12)", color: "#a78bfa", border: "1px solid rgba(124,58,237,0.25)" }}>
              100% TypeScript
            </span>
          </div>

          {/* Title */}
          <div className="mb-5">
            <h2 className="text-5xl md:text-7xl font-black text-white tracking-tight mb-3"
              style={{ textShadow: "0 0 60px rgba(37,99,235,0.4)" }}>
              Med<span style={{ color: "#2563eb" }}>Sync</span>
            </h2>
            <p className="text-lg md:text-xl text-slate-300 font-medium">
              Digital Health Platform — Patients · Doctors · Admin
            </p>
            <p className="text-slate-500 text-sm mt-2 max-w-2xl leading-relaxed">
              A production-deployed, full-stack healthcare SaaS built with Next.js 16, PostgreSQL, Socket.io,
              Zoom API, and Google Gemini AI. End-to-end from booking to video consultation to AI-parsed lab reports.
            </p>
          </div>

          {/* Metrics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">
            {METRICS.map((m) => (
              <div key={m.label} className="flex items-center gap-3 px-4 py-3 rounded-xl"
                style={{ background: `${m.color}10`, border: `1px solid ${m.color}25` }}>
                <m.icon size={16} style={{ color: m.color }} className="flex-shrink-0" />
                <div>
                  <p className="text-lg font-black text-white leading-none">{m.value}</p>
                  <p className="text-[10px] text-slate-500 mt-0.5">{m.label}</p>
                </div>
              </div>
            ))}
          </div>

          {/* CTAs */}
          <div className="flex flex-wrap gap-3 mb-5">
            <motion.a href={LINKS.live} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white relative overflow-hidden group"
              style={{ background: "linear-gradient(135deg, #1d4ed8, #2563eb)" }}
              whileHover={{ scale: 1.04, y: -2 }} whileTap={{ scale: 0.97 }}>
              <span className="absolute inset-0 bg-white/0 group-hover:bg-white/10 transition-colors" />
              <Globe size={15} className="relative" />
              <span className="relative">Live App</span>
              <ExternalLink size={12} className="relative opacity-70" />
            </motion.a>

            <motion.a href={LINKS.github} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-slate-300 hover:text-white glass border border-white/[0.1] hover:border-white/[0.2] transition-all"
              whileHover={{ scale: 1.04, y: -2 }} whileTap={{ scale: 0.97 }}>
              <Github size={15} />
              GitHub Repo
            </motion.a>

            <motion.a href={`${LINKS.api}/health`} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-slate-400 hover:text-white glass border border-white/[0.08] hover:border-emerald-400/20 transition-all"
              whileHover={{ scale: 1.04, y: -2 }} whileTap={{ scale: 0.97 }}>
              <Activity size={15} />
              API Health
            </motion.a>
          </div>

          {/* Deployment info */}
          <div className="flex flex-wrap gap-3">
            {[
              { label: "Frontend", value: "Vercel", color: "#ffffff" },
              { label: "Backend",  value: "Render", color: "#46e3b7" },
              { label: "Database", value: "Neon PostgreSQL", color: "#00E5BF" },
              { label: "Auth",     value: "JWT + Google OAuth", color: "#4285F4" },
            ].map(item => (
              <span key={item.label} className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs"
                style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}>
                <span className="text-slate-500">{item.label}:</span>
                <span className="font-medium" style={{ color: item.color }}>{item.value}</span>
              </span>
            ))}
          </div>
        </div>
      </motion.div>

      {/* ── TECH STACK ───────────────────────────────────────────────────── */}
      <motion.div variants={fadeInUp} className="flex flex-wrap gap-2 mb-6">
        {TECH.map((t) => (
          <span key={t.name}
            className="px-3 py-1.5 rounded-xl glass border border-white/[0.07] text-xs font-medium text-slate-300 hover:text-white transition-colors cursor-default flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: t.color }} />
            {t.name}
          </span>
        ))}
      </motion.div>

      {/* ── 3-ROLE PORTAL OVERVIEW ───────────────────────────────────────── */}
      <motion.div variants={fadeInUp} className="mb-6">
        <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-5 flex items-center gap-2">
          <span className="w-4 h-px bg-slate-700" />
          Three Portals, One Platform
          <span className="flex-1 h-px bg-slate-700/50" />
        </p>

        {/* Portal tabs */}
        <div className="flex gap-2 mb-5 flex-wrap">
          {PORTALS.map((p, i) => (
            <motion.button
              key={p.role}
              onClick={() => setActivePortal(i)}
              className={`flex items-center gap-2.5 px-5 py-2.5 rounded-xl text-sm font-semibold transition-all duration-300 ${
                activePortal === i ? "text-white shadow-lg" : "text-slate-400 hover:text-white glass border border-white/[0.08]"
              }`}
              style={activePortal === i ? {
                background: `linear-gradient(135deg, ${p.color}dd, ${p.color})`,
                boxShadow: `0 0 20px ${p.color}40`,
              } : {}}
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
            >
              <p.icon size={15} />
              {p.role}
            </motion.button>
          ))}
        </div>

        <AnimatePresence mode="wait">
          {PORTALS.map((portal, pi) => pi === activePortal && (
            <motion.div key={portal.role}
              initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }}
              transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="p-5 rounded-2xl glass border border-white/[0.07] relative overflow-hidden mb-4">
                <div className="absolute inset-0 pointer-events-none rounded-2xl"
                  style={{ background: `radial-gradient(circle at 0% 0%, ${portal.glow} 0%, transparent 60%)` }} />
                <div className="relative z-10 grid sm:grid-cols-2 xl:grid-cols-4 gap-3">
                  {portal.features.map((f) => (
                    <div key={f.label} className="flex items-start gap-3 p-3 rounded-xl bg-white/[0.03] hover:bg-white/[0.05] transition-colors group">
                      <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"
                        style={{ background: `${portal.color}18` }}>
                        <f.icon size={14} style={{ color: portal.color }} />
                      </div>
                      <div className="min-w-0">
                        <p className="text-xs font-bold text-white group-hover:text-white/90">{f.label}</p>
                        <p className="text-[10px] text-slate-500 mt-0.5 leading-relaxed">{f.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </motion.div>

      {/* ── ARCHITECTURE DIAGRAM ─────────────────────────────────────────── */}
      <motion.div variants={fadeInUp} className="mb-6">
        <ArchDiagram />
      </motion.div>

      {/* ── THIRD-PARTY INTEGRATIONS ─────────────────────────────────────── */}
      <motion.div variants={fadeInUp} className="mb-6">
        <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-5 flex items-center gap-2">
          <span className="w-4 h-px bg-slate-700" />
          Third-Party Integrations
          <span className="flex-1 h-px bg-slate-700/50" />
        </p>
        <motion.div variants={staggerContainer} className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">
          {INTEGRATIONS.map((intg) => (
            <motion.div key={intg.name} variants={cardReveal}
              className="group p-5 rounded-2xl glass border border-white/[0.07] hover:border-white/[0.14] transition-all duration-300 relative overflow-hidden"
              whileHover={{ y: -4 }} transition={{ type: "spring", stiffness: 300, damping: 20 }}>
              <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-400 rounded-2xl"
                style={{ background: `radial-gradient(circle at 0% 0%, ${intg.color}10 0%, transparent 65%)` }} />
              <div className="relative z-10">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0"
                    style={{ background: `${intg.color}15` }}>
                    <intg.icon size={17} style={{ color: intg.color }} />
                  </div>
                  <div>
                    <p className="text-sm font-bold text-white">{intg.name}</p>
                    <p className="text-[10px] font-mono" style={{ color: intg.color }}>{intg.type}</p>
                  </div>
                </div>
                <p className="text-slate-400 text-xs leading-relaxed">{intg.desc}</p>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </motion.div>

      {/* ── AUTH & SECURITY ───────────────────────────────────────────────── */}
      <motion.div variants={fadeInUp} className="mb-6">
        <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-5 flex items-center gap-2">
          <span className="w-4 h-px bg-slate-700" />
          Authentication & Security
          <span className="flex-1 h-px bg-slate-700/50" />
        </p>
        <div className="grid md:grid-cols-2 gap-4">
          {/* Auth flow */}
          <div className="p-5 rounded-2xl glass border border-white/[0.07]">
            <div className="flex items-center gap-2 mb-4">
              <Lock size={14} className="text-blue-400" />
              <p className="text-sm font-bold text-white">Dual-Token JWT Flow</p>
            </div>
            <div className="flex flex-col gap-2">
              {[
                { step: "Register",  color: "#2563eb", desc: "bcryptjs (10 rounds) → User + role profile in Prisma transaction" },
                { step: "Login",     color: "#0891b2", desc: "Access token (30min HS256) + Refresh token (7 days, stored in DB)" },
                { step: "Refresh",   color: "#7c3aed", desc: "Client sends refresh → server validates → new access token → old deleted (rotation)" },
                { step: "G-OAuth",   color: "#4285F4", desc: "Google ID token → google-auth-library verify → upsert User → JWT pair" },
                { step: "Forgot PW", color: "#16a34a", desc: "randomBytes(32) hex token → stored with 1hr expiry → Resend reset email" },
                { step: "Reset PW",  color: "#f59e0b", desc: "Token verified → new hash → update password + mark token used + delete all refresh tokens" },
              ].map((s) => (
                <div key={s.step} className="flex items-start gap-2.5">
                  <span className="text-[9px] font-bold px-2 py-0.5 rounded mt-0.5 flex-shrink-0"
                    style={{ background: `${s.color}15`, color: s.color }}>{s.step}</span>
                  <p className="text-[11px] text-slate-400 leading-relaxed">{s.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Security layers */}
          <div className="p-5 rounded-2xl glass border border-white/[0.07]">
            <div className="flex items-center gap-2 mb-4">
              <Shield size={14} className="text-emerald-400" />
              <p className="text-sm font-bold text-white">Security Layers</p>
              <span className="text-[10px] px-2 py-0.5 rounded-full font-bold"
                style={{ background: "rgba(52,211,153,0.12)", color: "#34d399" }}>Production-grade</span>
            </div>
            <div className="flex flex-col gap-3">
              {[
                { label: "Helmet",         color: "#ef4444", desc: "14 HTTP security headers: CSP, HSTS, X-Frame-Options, X-Content-Type-Options" },
                { label: "Rate Limiting",  color: "#f59e0b", desc: "Auth: 20 req/15min · API: 120 req/min (express-rate-limit)" },
                { label: "CORS",           color: "#3b82f6", desc: "Strict origin allowlist · credentials: true · comma-sep multi-origin support" },
                { label: "Prisma",         color: "#5a67d8", desc: "Parameterized queries by default — zero raw SQL injection surface" },
                { label: "Token Rotation", color: "#16a34a", desc: "Single-use refresh tokens · all tokens invalidated on password reset" },
                { label: "Doctor Gate",    color: "#7c3aed", desc: "isApproved=false on register · Admin must approve before login is allowed" },
              ].map((s) => (
                <div key={s.label} className="flex items-start gap-2.5">
                  <span className="w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0" style={{ background: s.color }} />
                  <div>
                    <span className="text-[11px] font-semibold" style={{ color: s.color }}>{s.label}: </span>
                    <span className="text-[11px] text-slate-400">{s.desc}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </motion.div>

      {/* ── ENGINEERING CHALLENGES ───────────────────────────────────────── */}
      <motion.div variants={fadeInUp} className="mb-6">
        <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-5 flex items-center gap-2">
          <span className="w-4 h-px bg-slate-700" />
          Production Bugs Solved
          <span className="flex-1 h-px bg-slate-700/50" />
          <span className="text-[10px] text-slate-600 normal-case font-sans">6 real bugs diagnosed and fixed in production</span>
        </p>
        <div className="flex flex-col gap-3">
          {CHALLENGES.map((c, i) => (
            <motion.div key={c.title} variants={cardReveal}
              className="rounded-2xl overflow-hidden border border-white/[0.07] hover:border-white/[0.12] transition-all duration-300">
              <button
                onClick={() => setExpandedChallenge(expandedChallenge === i ? null : i)}
                className="w-full flex items-center justify-between px-5 py-4 glass text-left group"
              >
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
                    style={{ background: `${c.categoryColor}15` }}>
                    <Layers size={13} style={{ color: c.categoryColor }} />
                  </div>
                  <div>
                    <span className="text-sm font-semibold text-white group-hover:text-blue-400 transition-colors">
                      {c.title}
                    </span>
                    <span className="ml-3 text-[10px] font-bold px-2 py-0.5 rounded-full"
                      style={{ background: `${c.categoryColor}15`, color: c.categoryColor }}>
                      {c.category}
                    </span>
                  </div>
                </div>
                <motion.div animate={{ rotate: expandedChallenge === i ? 180 : 0 }} transition={{ duration: 0.25 }}>
                  <ChevronDown size={16} className="text-slate-500" />
                </motion.div>
              </button>

              <AnimatePresence>
                {expandedChallenge === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
                    className="overflow-hidden"
                  >
                    <div className="px-5 pb-5 border-t border-white/[0.05]">
                      <div className="grid md:grid-cols-2 gap-4 mt-4">
                        <div>
                          <p className="text-[10px] font-mono text-red-400/70 uppercase tracking-wider mb-2">Problem</p>
                          <p className="text-slate-400 text-xs leading-relaxed">{c.problem}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-mono text-emerald-400/70 uppercase tracking-wider mb-2">Solution</p>
                          <p className="text-slate-400 text-xs leading-relaxed">{c.solution}</p>
                        </div>
                      </div>
                      {c.code && <CodeBlock code={c.code} label={`${c.category.toLowerCase()}-fix.ts`} />}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* ── NUMBERS ROW ──────────────────────────────────────────────────── */}
      <motion.div variants={fadeInUp}
        className="p-6 rounded-2xl glass border border-white/[0.07] overflow-hidden relative">
        <div className="absolute inset-0 pointer-events-none"
          style={{ background: "radial-gradient(circle at 50% 100%, rgba(37,99,235,0.07) 0%, transparent 70%)" }} />
        <p className="text-xs font-mono text-slate-500 uppercase tracking-widest mb-5 text-center">By the Numbers</p>
        <div className="grid grid-cols-4 md:grid-cols-8 gap-4">
          {NUMBERS.map((n, i) => (
            <div key={n.label} className={`text-center ${i < 7 ? "md:border-r md:border-white/[0.05]" : ""}`}>
              <p className="text-xl md:text-2xl font-black" style={{
                background: "linear-gradient(135deg, #60a5fa, #34d399)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
                backgroundClip: "text",
              }}>
                {n.value}
              </p>
              <p className="text-[10px] text-slate-500 mt-1 leading-tight">{n.label}</p>
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}
